#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DB_USER} WITH LOGIN PASSWORD '${DB_USER_PW}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DB_USER};
    GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE executive TO ${DB_USER};
    GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE manager TO ${DB_USER};
    GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE employee TO ${DB_USER};
EOSQL
